### ISSUE TITLE
Standardize and finalize column names

### ISSUE THREAD

**Issue by jdq22** [royrapoport/channelstats#2]
- Change all references to a channel's ID to slack_cid. Channel.channel_id should be Channel.slack_cid.
- Change Channel.channel_name to Channel.friendly_name.
- Change all columns named `key` to something else since `key` is a reserved word.
- Remove deprecated columns, i.e., ChannelConfiguration.refetch.
- Rewrite documentation on Configuration table to include specifics about existing Configurations.
- Change all Slack-provided IDs to be prefixed with `slack_`. Change FirstPost.key to FirstPost.slack_uid.
- Change Message-yyyy-mm-dd.thread_author to Message-yyyy-mm-dd.parent_user_id, so that the name mirrors the name in Slack's API.
- Change Message-yyyy-mm-dd.wordcount to Message-yyyy-mm-dd.word_count.
- Are Message-yyyy-mm-dd.replies guaranteed to be sorted by timestamp ascending? Indicate answer in documentation.
- Add is_thread_head (bool, only exists when set to True) and is_threaded (bool, only exists when set to True).
- Consider standardizing the delimiter in lists. Sometimes we use ":", and sometimes we use ",".
- Change User.id to User.slack_uid.
- Change all `timestamp` named columns to `ts`.

**Comment by royrapoport** [comment]
Complete
