### ISSUE TITLE
config.py should be in .gitignore and there should be a template file in the repo

### ISSUE THREAD

**Issue by ax42** [royrapoport/channelstats#9]

**Comment by royrapoport** [comment]
I've created PR #10 to add config.py to .gitignore.  As it currently resides in the repo, I think it's a decent template, so I don't **think** we need to do anything further, but @ax42 interested in your perspective. If you agree, feel free to close.

**Comment by ax42** [comment]
I would put the link https://docs.aws.amazon.com/general/latest/gr/rande.html#ddb_region into the file.  I found it useful when trying to fill in the 'region' parameter.

**Comment by jdq22** [comment]
Added the link to the region documentation here: https://github.com/royrapoport/channelstats/pull/14

**Comment by royrapoport** [comment]
This, I believe, is now complete.
